version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    network_mode: host
    command: tunnel run --token-file /token.txt
    volumes:
      - /volume1/docker/cloudflared/cloudflared-token.txt:/token.txt:ro